package com.ypsi.fundamentalism.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.ypsi.fundamentalism.FundamentalPrinciples;
import com.ypsi.fundamentalism.event.Visitors;
import io.redspace.ironsspellbooks.api.registry.SpellRegistry;
import io.redspace.ironsspellbooks.api.spells.AbstractSpell;
import net.minecraft.server.packs.resources.ResourceManagerReloadListener;
import net.minecraft.world.level.block.LevelEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.event.AddReloadListenerEvent;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import org.objectweb.asm.ClassReader;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

@EventBusSubscriber(modid = FundamentalPrinciples.MOD_ID)
public class SpellCategoriesConfig {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static File configFile;
    private static SpellCategoriesConfig instance;

    public Map<String, List<String>> spellCategories = new HashMap<>();
    public boolean autoGenerated = false;
    public boolean analysisCompleted = false;

    public static SpellCategoriesConfig getInstance() {
        if (instance == null) {
            instance = new SpellCategoriesConfig();
        }
        return instance;
    }

    private SpellCategoriesConfig() {
        initializeEmptyCategories();
    }

    public static void initialize(File configDir) {
        configFile = new File(configDir, "fundamentalism/spell_categories.json");
        getInstance().loadFromFile();
    }

    private void loadFromFile() {
        if (configFile.exists()) {
            try (FileReader reader = new FileReader(configFile)) {
                SpellCategoriesConfig loaded = GSON.fromJson(reader, SpellCategoriesConfig.class);
                this.spellCategories = loaded.spellCategories;
                this.autoGenerated = loaded.autoGenerated;
                this.analysisCompleted = loaded.analysisCompleted;
                System.out.println("Config Saved: " + configFile.getAbsolutePath());
            } catch (IOException e) {
                System.err.println("Error loading config: " + e.getMessage());
            }
        } else {
            System.out.println("Config file not founded, generating a new one.");
        }
        save();
    }

    public void generateCategoriesFromRegistry() {
//        if (analysisCompleted ) {
//            System.out.println("Spell Categorization Completed");
//            return;
//        }
        System.out.println("=== STARTING SPELL ANALYSING ===");
        System.out.println("Analysing...");

        initializeEmptyCategories();

        Map<String, String> categoryMapping = Map.ofEntries(
                Map.entry("createsEntity", "createEntity"),
                Map.entry("createsProjectile", "usesShoot"),
                Map.entry("usesShoot", "usesShoot"),
                Map.entry("usesSummon", "usesSummon"),
                Map.entry("usesTargeting", "usesTargeting"),
                Map.entry("hasRecasts", "hasRecasts"),
                Map.entry("usesTeleport", "usesTeleport"),
                Map.entry("usesAddEffect", "addEffects"),
                Map.entry("createsAoeEntity", "createsAoeEntities"),
                Map.entry("usesImpulseCastData", "usesMobility"),
                Map.entry("usesRaycast", "usesRaycast"),
                Map.entry("usesHealing", "usesHealing"),
                Map.entry("usesPotentiation", "usesPotentiation")
        );

        SpellRegistry.REGISTRY.forEach(spell -> {
            try {
                String spellId = spell.getSpellId();
                System.out.println("Spell: " + spellId);

                Visitors.SpellAnalysisVisitor visitor = analyzeSpellClass(spell);
                Set<String> detectedCategories = visitor.getDetectedCategories();

                for (String detectedCategory : detectedCategories) {
                    String systemCategory = categoryMapping.get(detectedCategory);
                    if (systemCategory != null) {
                        if ("hasRecasts".equals(systemCategory) && detectedCategories.contains("usesSummon")) {
                            continue;
                        }
                        addToCategory(systemCategory, spellId);
                    }
                }
            } catch (Exception e) {
                System.err.println("Error with spell: " + spell.getSpellId() + " - " + e.getMessage());
            }
        });

        this.autoGenerated = true;
        this.analysisCompleted = true;
        save();

        System.out.println("=== Completed ===");
        for (Map.Entry<String, List<String>> entry : spellCategories.entrySet()) {
            System.out.println(entry.getKey() + ": " + entry.getValue().size() + " spells");
        }
        System.out.println("Filed saved : " + configFile.getAbsolutePath());
    }

    private void initializeEmptyCategories() {
        String[] categories = {
                "createEntity", "usesShoot", "usesSummon", "usesTargeting",
                "hasRecasts", "usesTeleport", "addEffects",
                "createsAoeEntities", "usesMobility", "usesRaycast",
                "usesHealing", "usesPotentiation"
        };

        for (String category : categories) {
            spellCategories.put(category, new ArrayList<>());
        }
    }

    private void addToCategory(String category, String spellId) {
        if (spellCategories.containsKey(category) && !spellCategories.get(category).contains(spellId)) {
            spellCategories.get(category).add(spellId);
        }
    }

    public boolean isInCategory(String spellId, String category) {
        return spellCategories.getOrDefault(category, Collections.emptyList()).contains(spellId);
    }

    public List<String> getSpellsInCategory(String category) {
        return spellCategories.getOrDefault(category, Collections.emptyList());
    }

    public Set<String> getCategoriesForSpell(String spellId) {
        Set<String> categories = new HashSet<>();
        for (Map.Entry<String, List<String>> entry : spellCategories.entrySet()) {
            if (entry.getValue().contains(spellId)) {
                categories.add(entry.getKey());
            }
        }
        return categories;
    }

    private Visitors.SpellAnalysisVisitor analyzeSpellClass(AbstractSpell spell) throws IOException {
        String className = spell.getClass().getName().replace('.', '/');
        ClassReader classReader = new ClassReader(className);
        Visitors.SpellAnalysisVisitor visitor = new Visitors.SpellAnalysisVisitor();
        classReader.accept(visitor, ClassReader.SKIP_DEBUG);
        return visitor;
    }

    public void save() {
        try {
            configFile.getParentFile().mkdirs();
            try (FileWriter writer = new FileWriter(configFile)) {
                GSON.toJson(this, writer);
                System.out.println("Config saved: " + configFile.getAbsolutePath());
            }
        } catch (IOException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    // Eventos para generar las categorías automáticamente
    @SubscribeEvent
    public static void onServerStarted(ServerStartedEvent event) {
            System.out.println("Generating config file for new world...");
            getInstance().generateCategoriesFromRegistry();
    }

    @SubscribeEvent
    public static void onAddReloadListeners(AddReloadListenerEvent event) {
        System.out.println("Reloading spell config...");
    }
}
