package com.ypsi.fundamentalism.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.ypsi.fundamentalism.FundamentalPrinciples;
import com.ypsi.fundamentalism.event.Visitors;
import io.redspace.ironsspellbooks.api.registry.SpellRegistry;
import io.redspace.ironsspellbooks.api.spells.AbstractSpell;
import net.minecraft.client.telemetry.events.WorldLoadEvent;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.player.Player;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerAboutToStartEvent;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import org.objectweb.asm.ClassReader;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;

import static com.ypsi.fundamentalism.FundamentalPrinciples.LOGGER;

@EventBusSubscriber(modid = FundamentalPrinciples.MOD_ID)
public class SpellCategoriesGenerator {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private static ConfigOutput loadedConfig = null;
    private static final File CONFIG_FILE = new File("config/fundamentalism/spell_categories.json");


    @SubscribeEvent
    public static void onCommonSetup(FMLCommonSetupEvent event) {
        LOGGER.info("Common Setup - Generating spell categories");
        generateCategoriesFromRegistry();
    }


    public static void generateCategoriesFromRegistry() {
        LOGGER.info("GENERATING SPELL CATEGORIES...");

        try {
            LOGGER.info("-> SpellRegistry size: {}", SpellRegistry.REGISTRY.size());

            Map<String, List<String>> spellCategories = new HashMap<>();
            initializeEmptyCategories(spellCategories);

            Map<String, String> categoryMapping = createCategoryMapping();

            SpellRegistry.REGISTRY.forEach(spell -> {
                try {
                    String spellId = spell.getSpellId().toString();
                    LOGGER.info("<><><> Analyzing: {}", spellId);

                    Visitors.SpellAnalysisVisitor visitor = analyzeSpellClass(spell);
                    Set<String> detectedCategories = visitor.getDetectedCategories();

                    LOGGER.info("   Detected: {}", detectedCategories);

                    for (String detectedCategory : detectedCategories) {
                        String systemCategory = categoryMapping.get(detectedCategory);
                        if (systemCategory != null) {
                            if ("hasRecasts".equals(systemCategory) && detectedCategories.contains("usesSummon")) {
                                continue;
                            }
                            addToCategory(spellCategories, systemCategory, spellId);
                        }
                    }
                } catch (Exception e) {
                    LOGGER.error("Error with spell: {} - {}", spell.getSpellId(), e.getMessage());
                }
            });

            ConfigOutput configOutput = new ConfigOutput();
            configOutput.spellCategories = spellCategories;
            configOutput.autoGenerated = true;
            configOutput.analysisCompleted = true;

            saveToFile(configOutput);
            loadedConfig = configOutput;

            printSummary(spellCategories);

        } catch (Exception e) {
            LOGGER.error("Error generating spell categories: {}", e.getMessage(), e);
        }
    }

    private static Map<String, String> createCategoryMapping() {
        Map<String, String> mapping = new HashMap<>();
        mapping.put("createsEntity", "createEntity");
        mapping.put("createsProjectile", "usesShoot");
        mapping.put("usesShoot", "usesShoot");
        mapping.put("usesSummon", "usesSummon");
        mapping.put("usesTargeting", "usesTargeting");
        mapping.put("hasRecasts", "hasRecasts");
        mapping.put("usesTeleport", "usesTeleport");
        mapping.put("usesAddEffect", "addEffects");
        mapping.put("createsAoeEntity", "createsAoeEntities");
        mapping.put("usesImpulseCastData", "usesMobility");
        mapping.put("usesRaycast", "usesRaycast");
        mapping.put("usesHealing", "usesHealing");
        mapping.put("usesPotentiation", "usesPotentiation");
        mapping.put("immutable", "immutable");
        return mapping;
    }

    private static Visitors.SpellAnalysisVisitor analyzeSpellClass(AbstractSpell spell) throws IOException {
        String className = spell.getClass().getName().replace('.', '/');
        LOGGER.info("🤑 ASM Analyzing: {}", className);

        String classResource = className + ".class";

        try (InputStream classStream = spell.getClass().getClassLoader().getResourceAsStream(classResource)){
            if (classStream == null) {
                LOGGER.error("Cannot find class resource: {}", classResource);
                return new Visitors.SpellAnalysisVisitor();
            }
            ClassReader classReader = new ClassReader(classStream);
            LOGGER.info("ClassReader created for: {}", className);

            Visitors.SpellAnalysisVisitor visitor = new Visitors.SpellAnalysisVisitor();
            classReader.accept(visitor, ClassReader.SKIP_DEBUG);

            LOGGER.info("ASM analysis completed for: {}", className);
            LOGGER.info("-> Detected: {}", visitor.getDetectedCategories());

            return visitor;
        } catch (RuntimeException e) {
            LOGGER.error("ASM FAILED for: {} - {}", spell.getSpellId(), e.getMessage(), e);
            return new Visitors.SpellAnalysisVisitor();
        }

    }

    private static void initializeEmptyCategories(Map<String, List<String>> categories) {
        String[] categoryNames = {
                "createEntity", "usesShoot", "usesSummon", "usesTargeting",
                "hasRecasts", "usesTeleport", "addEffects",
                "createsAoeEntities", "usesMobility", "usesRaycast",
                "usesHealing", "usesPotentiation","immutable"
        };
        for (String category : categoryNames) {
            categories.put(category, new ArrayList<>());
        }
    }

    private static void addToCategory(Map<String, List<String>> categories, String category, String spellId) {
        if (categories.containsKey(category) && !categories.get(category).contains(spellId)) {
            categories.get(category).add(spellId);
        }
    }

    private static void saveToFile(ConfigOutput config) {
        CONFIG_FILE.getParentFile().mkdirs();
        try (FileWriter writer = new FileWriter(CONFIG_FILE)) {
            GSON.toJson(config, writer);
            LOGGER.info("ServerConfig saved to: {}", CONFIG_FILE.getAbsolutePath());
        } catch (IOException e) {
            LOGGER.info("Error saving config: {}", e.getMessage());
        }
    }

    private static void printSummary(Map<String, List<String>> categories) {
        LOGGER.info("\n=== GENERATION SUMMARY ===");
        int totalSpells = 0;
        Set<String> uniqueSpells = new HashSet<>();

        for (Map.Entry<String, List<String>> entry : categories.entrySet()) {
            LOGGER.info("  {}: {} spells", entry.getKey(), entry.getValue().size());
            uniqueSpells.addAll(entry.getValue());
            totalSpells += entry.getValue().size();
        }

        LOGGER.info("Total unique spells: {}", uniqueSpells.size());
        LOGGER.info("Total category entries: {}", totalSpells);
        LOGGER.info("=== GENERATION COMPLETED ===");
    }
    public static boolean isInCategory(String spellId, String category) {
        if (loadedConfig == null) return false;
        return loadedConfig.spellCategories.getOrDefault(category, Collections.emptyList()).contains(spellId);
    }

    public static List<String> getSpellsInCategory(String category) {
        if (loadedConfig == null) return Collections.emptyList();
        return new ArrayList<>(loadedConfig.spellCategories.getOrDefault(category, Collections.emptyList()));
    }

    public static Set<String> getCategoriesForSpell(String spellId) {
        if (loadedConfig == null) return Collections.emptySet();
        Set<String> categories = new HashSet<>();
        for (Map.Entry<String, List<String>> entry : loadedConfig.spellCategories.entrySet()) {
            if (entry.getValue().contains(spellId)) {
                //if(!entry.getKey().contains("immutable")) {
                    categories.add(entry.getKey());
                //}
            }
        }
        return categories;
    }

    private static class ConfigOutput {
        public Map<String, List<String>> spellCategories = new HashMap<>();
        public boolean autoGenerated = false;
        public boolean analysisCompleted = false;
    }
}
